### PR TITLE
[16.0][MIG] account_budget_oca: Migration to version 16.0

### PR DESCRIPTION
**Pull request by polqubiq**

### CODE REVIEW

**Comment by polqubiq** [comment]
Good morning @pedrobaeza, is everything correct? It tells me an error in the tests which is:
`ValueError: External ID not found in the system: account.data_account_type_revenue`
But I don't really know if this bug is outside the scope of this `PR`.
If this is not the case, could you advise me on how I should proceed?

Thank you!

**Comment by pedrobaeza** [comment]
You have to talk in this repository in English. The error about the XML-ID `account.data_account_type_revenue` is because this has changed and now there's not anymore `account.account.type` model. You should adjust the code to this condition.

**Comment by polqubiq** [comment]
> You have to talk in this repository in English. The error about the XML-ID `account.data_account_type_revenue` is because this has changed and now there's not anymore `account.account.type` model. You should adjust the code to this condition.

Good morning @pedrobaeza I have already completed the migration of the module correctly!

On the other hand, the fact that the `account.account.type` model does not exist in `v16` **may need to be added in the migration guide**, at least that the `user_type_id` field was a `Many2one` related to `account.account.type` and that now has been replaced by a field called `account_type` and is a `selection` field.

Thank you.

**Comment by pedrobaeza** [comment]
That is not a framework change, but a datamodel/data one that you should research and apply on migrations.

The migration guide is only for framework changes. If not, there are literally thousand of datamodel changes (see https://github.com/OCA/OpenUpgrade/commit/a060a7657790784fe2d129e9d0550277483d019b), and the guide won't be useful in that case, apart from not always having a replacement one, or it depends on the context. Dumping all of this in a guide is barely impossible, or as said, not practical. It can be debatable though if people want to contribute to a guide of this kind, but apart from the existing one.

**Comment by PaolaEras** [comment]
@pedrobaeza after testing functionally the module migrated, I consider it to be working correctly.
The operation has also been compared with v14 and I don't find any errors, it would be interesting to have the module fully operational for v16

**Comment by pedrobaeza** [comment]
OK, just approve it using the GitHub flow, and other qualified reviewer should review the PR. You can review other PRs and ask in exchange that they review yours.

**Review by PaolaEras — APPROVED** [review]

**Review by chaojuunzhou — APPROVED** [review]

**Comment by chaojuunzhou** [comment]
Code reviewed and functionally tested

**Comment by polqubiq** [comment]
Good morning @pedrobaeza, is everything okay?

Greetings!

**Comment by pedrobaeza** [comment]
Well, none of the reviewers are PSC/maintainers, but let's unlock it. Please increase your activity on OCA, doing more reviews on other PRs apart from yours, and you'll increase your trustability.

/ocabot merge nobump

**Comment by polqubiq** [comment]
@pedrobaeza parece que se iba a mergear el `PR`, pero no se ha hecho del todo. ¿Sabes qué ha ocurrido?

**Pull request merged**
