### PR TITLE
[14.0][MIG] account_budget_oca

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Freni-OSI can you squash all the automated commits ([UPD], Translations and .pot). to cleanup the commit history.

**Comment by Freni-OSI** [comment]
> @Freni-OSI can you squash all the automated commits ([UPD], Translations and .pot). to cleanup the commit history.

It's Done.

**Review by patrickrwilson — APPROVED** [review]
Thanks for migrating, worked on my test instance. LGTM

**Comment by patrickrwilson** [comment]
@osi-scampbell @smangukiya can you help review this?

**Review by smangukiya — APPROVED** [review]
@patrickrwilson : On runbot I was not able to create "Budgetary Position" with accounting billing user or billing administrator. Can you confirm that part is working? I mean create button is not visible.

image

**Comment by patrickrwilson** [comment]
@Freni-OSI Please see @smangukiya comment, I've confirmed this happens in community also. I'm not exactly sure why but can you take a look please, perhaps there is a access group change.

**Comment by Freni-OSI** [comment]
> @Freni-OSI Please see @smangukiya comment, I've confirmed this happens in community also. I'm not exactly sure why but can you take a look please, perhaps there is a access group change.

Hi, for that, the user has to enable - "Show Full Accounting Features" group. (as this access right is added in the security file)
CC: @smangukiya  @patrickrwilson

**Comment by patrickrwilson** [comment]
> Hi, for that, the user has to enable - "Show Full Accounting Features" group. (as this access right is added in the security file)

Yep, that was it, thanks @Freni-OSI. This should be good to go now.

**Comment by smangukiya** [comment]
> > @Freni-OSI Please see @smangukiya comment, I've confirmed this happens in community also. I'm not exactly sure why but can you take a look please, perhaps there is a access group change.
> 
> Hi, for that, the user has to enable - "Show Full Accounting Features" group. (as this access right is added in the security file)
> CC: @smangukiya @patrickrwilson

@Freni-OSI : Thank you for your contribution!

**Comment by matias-costa** [comment]
## Corrección aplicada

Commit `728f106`:

**`view_mode="list,form"` → `"tree,form"` en `action_billing_customers`** (`menus.xml`)

En Odoo 17 el modo de vista lista se llama `tree`, no `list`. Con `list` la acción no abría la vista correctamente. El resto del módulo ya usaba `tree,form` — era un typo aislado en esta acción.

**Pull request merged**
