### PR TITLE
[ADD] new module account_budget_template and migrate to 12.0

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Review by dalonsod — APPROVED** [review]
LGTM

**Review by anajuaristi — APPROVED** [review]

**Comment by anajuaristi** [comment]
@pedrobaeza Thank you!!!

**Comment by pedrobaeza** [comment]
There's a problem with translations:
```
./account_budget_oca/i18n/vi.po:306: duplicate message definition...
./account_budget_oca/i18n/vi.po:302: ...this is the location of the first definition
```
Please fix it in other PR.

**Pull request closed without merging**
