### PR TITLE
[IMP] Do not show analytic account closed or cancel when creating a new ...

### PR DESCRIPTION
**Pull request by vrenaville**
...budget line

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lepistone** [comment]
- The travis failure is unrelated to this fix. I restarted the build in case it's fixes with the fix we did yesterday.
- Nitpicking 1: a short first line of the commit message would be better (optionally followed by an empty line, and other line wrapped around 72.
- Nitpicking 2: I would split the diff line fixing whitespace in another commit.

No need to fix nitpickings yourself @vrenaville I :+1: , and I can take care of those when merging. Thanks!

**Comment by gurneyalex** [comment]
:+1:

**Comment by lepistone** [comment]
Hang on, I'm merging manually. Thanks

**Comment by lepistone** [comment]
merged

**Pull request closed without merging**
