### PR TITLE
[ADD] account_budget_purchase

### PR DESCRIPTION
**Pull request by clonedagain**
New module to let budget managers optionally add or subtract the amount of the purchase orders not yet invoiced to/from the amounts of general accounting.

Screencast: https://www.youtube.com/watch?v=E-LvMFiigsk

This come is handy when suppliers send the invoices very late (like every several months) and you want to watch the purchases before spending more cash.

This module should work fine and be useful all by itself.
Used along with purchase_budget_limit (module which blocks purchase orders when budgets are exhausted - https://code.launchpad.net/~numerigraphe-team/purchase-wkfl/7.0-add-purchase_budget_limit/+merge/219829), it lets our factory watch the real/anticipated vs expected cash flow for purchases.

This was initially proposed for account-financial-tools but it was pointed that this repo was more appropriate.

### CODE REVIEW

**Comment by nhomar** [comment]
@clonedagain 

IMHO, Purchases are not conceptually in the same "conceptual amount" than invoices.

A budget has 4 operative states:

A.- Approved (Planned in Budget)
B.- Compromised (Purchase Order)
C.- Invoiced (Invoice already in system)
D.- Paid (Invoices already paid on paymenst in advance)

I think the actual budget behavior has a leak of B and D, but theoretically is incorrect sum B + C (if we lost one of them in the sum).

We are losing this amount due to the fact we are overwritting _prac_amt totally, we should have a different method that include (B) and other method + field that sum (B + C).

Conceptually I don't approve this PR.

Regards.

**Comment by clonedagain** [comment]
I did make sure no amount is lost indeed.
super() is called and the results are send downstream, except for a single special-case: in the standard you can't have a budget position with no accounts, but no it is allowed so that we can make a position including only pending purchases.
For this special case I use 0 instead of super() as a starting point because super() throws an exception.

So I hope you may change your mind about this proposal.

**Comment by clonedagain** [comment]
I changed the top comment of the PR to reflect that the POs are added/subtracted to standard account positions, they don't replace them.

**Comment by nhomar** [comment]
@clonedagain 

```
I changed the top comment of the PR to reflect that the POs are added/subtracted to standard account positions, they don't replace them.
```

This is exactly what I think we can **not** do friend, the fact of show as "done amount" a quantity different of what is already invoiced is incorrect from a functiona PoV I read your code.

Proposal:

Add a new column and call it as "Compromised [or the word that fit better in english]" but the invoiced amount or "Practical Amount" always should come from accounting nothing else.

http://awesomescreenshot.com/0913456z9c

**Comment by clonedagain** [comment]
OK I see your point, I'm new to this to I'll trust you.
I think it could also include Sales Order to be generic.

Would you agree with the following specs ?
- module name "account_budget_orders"
- new tab on budget positions "Sale and Purchase Orders" after the 
  "Accounts" tab
- in that tab: checkbox to count purchases or not, and selectbox to 
  choose the sign
- in same tab: checkbox to count sales or not, and selectbox to choose 
  the sign
- in budgetline model+views, add 3 function fields:
  - "Sales Orders Amount" (only in form view) = sum of confirmed 
    non-invoiced sales
  - "Purchase Orders Amount" (only in form view) = sum of confirmed 
    non-invoiced purchases
  - "Anticipated Amount" (form view+tree view) = practical + SO + PO
- adapt purchase_budget_limit to use the new column instead of the old

Lionel

**Comment by nhomar** [comment]
Hello @clonedagain 

If you are open to extend the scope of your module it is great, let me be more concise in some new points regarding the specifications you mention.

In lines:

```
- module name "account_budget_orders"
```

IMHO Sales and Purchases are treated totally different from a functional PoV and even a technical PoV, because in every state on the Purchase Order the company can decide different approaches than in the Sale Order.

If It was in my hands decide the scope and design totally I would do in this way:

1.- Module called account_budget_purchase.

Where I included 2 New Amounts:
- Compromised amount [From PO in state "Confirmed and not on invoiced (to avoid sum twice the same amount)"]
- Practical Amount Including PO [Sum of actual practical amount from invoices/aml + PO] which is what you did already.

This module will not work correctly with module that activate "Analytic Distribution Fields" (be careful around that) if You

```
- new tab on budget positions "Sale and Purchase Orders" after the
"Accounts" tab
```

I am not quite sure around include Sales Orderd is a good Idea, because you have the hability to plan negative budgets (purchases) and positive budgets (income) then I think we should be more complex there, but IMHO is a topic for a separate module (or a second stage)

```
- in that tab: checkbox to count purchases or not, and selectbox to
choose the sign
```

IMHO if you separate already in different fields the computation, it can be in "Global Configuration" [1] a checkbox that add the ACL to show fields and/or install the module.

```
- in same tab: checkbox to count sales or not, and selectbox to choose
the sign.
```

IMHO if you separate already in different fields the computation, it can be in "Global Configuration" [1] a checkbox that add the ACL to show fields and/or install the module.

```
- in budgetline model+views, add 3 function fields:
      - "Sales Orders Amount" (only in form view) = sum of confirmed
non-invoiced sales
      - "Purchase Orders Amount" (only in form view) = sum of confirmed
non-invoiced purchases
      - "Anticipated Amount" (form view+tree view) = practical + SO + PO
- adapt purchase_budget_limit to use the new column instead of the old
```

1.- Module called account_budget_sales should be the best approach, but be careful, you need to be sure about the sign of what you are doing, I should think deeper in include sales on this process, because sales are not in your hands, and I think the amount should come from CRM + Sales Orders but it is other history.

In my experience we can play with several options, even including picking if you want, If I was you, I stay one module per model with them specific fields (one per sales, purchase and so on) but staty in purchase with a first one and the include other one better thought.

I hope it helps.

[1] https://docs.google.com/a/vauxoo.com/file/d/0B8r9xKtfgpVUQ1pvWDNGSWEycUk/edit?usp=drivesdk

**Comment by clonedagain** [comment]
OK, I'm all for the principle of a generic module + config options to 
install specific features as sub-modules.

We did something like this for the computation of the quantity available 
to promise (not yet on github):
- 1 "main" module[1] adds :
  - a single function field "stock available to promise" based on 
    virtual stock
  - and config options to decide how it's computed by installing 
    sub-modules
- 1 optional module[1] can subtract receptions from the main field
- 1 optional module[2] can add possible productions to the main field, 
  and create a field "production capability"
- 1 optional module[3] can add draft sales to the main field, and create 
  a field "quoted quantity"

[1] 
https://code.launchpad.net/~numerigraphe-team/stock-logistic-warehouse/7.0-add-stock-available/+merge/220758
[2] 
https://code.launchpad.net/~numerigraphe-team/stock-logistic-warehouse/7.0-add-stock-available-mrp/+merge/220764
[3] 
https://code.launchpad.net/~numerigraphe-team/stock-logistic-warehouse/7.0-add-stock-available-sale/+merge/220761

I could do the same for budgets: 1 main field based on the accounting + 
optional modules to change the way it's computed.
Would that work, and would it be useful?

Another question: should the "percentage" field use only accounting data 
or should it be base it on the "compromised" amount.

> This module will not work correctly with module that activate 
> "Analytic Distribution Fields" (be careful around that) if You
> 
> Why not?
> 
> I am not quite sure around include Sales Orderd is a good Idea, 
> because you have the hability to plan negative budgets (purchases) and 
> positive budgets (income) then I think we should be more complex 
> there, but IMHO is a topic for a separate module (or a second stage)
> OK my suggestion about sales was simplistic and I don't need it myself. 
> So I won't do it, I just want to make sure if it needs to be generic or not.

**Comment by bwrsandman** [comment]
There is a huge TODO in the manifest file, so I will mark this as WIP

**Comment by clonedagain** [comment]
@bwrsandman the TODO is here for later Odoo version: I don't think I can write a meaningful test if there isn't one upstream in the first place.

**Comment by clonedagain** [comment]
I'll rewrite this for v8 and propose a new approach following @nhomar's advice sometime later.
Thank you all for your reviews.

**Pull request closed without merging**
