### PR TITLE
[12.0][ADD] budget_control [WIP]

### PR DESCRIPTION
**Pull request by kittiu**
Note: supersede https://github.com/OCA/account-budgeting/pull/32

### CODE REVIEW

**Comment by damendieta** [comment]
hello, How I can help?

**Comment by kittiu** [comment]
> hello, How I can help?

@damendieta, you an start by testing and see if it fits your requirement, or give more feedback or working on some PRs if you could.

In any case, I think best way to get you start is, I will write a better version of documentation to get you started. Please give me some time as I was moved to other project at the moment, will be back soon. Meanwhile, you may install the budget_control_demo_full_cycle and the test script to see the process. 

Feel free to open new issue to discuss.

**Comment by damendieta** [comment]
Hi, I'm testing it now.

If you can, please update the readme to understand the logic behind this development. 

I'm reading the code to see what it does, but it's really time consuming. If you can give some tips to guide me it will be enough.

Also, could you please tell me the relationship between this modules and the other branches, for example, the branch budget-management is complementary to this or it's completely different development.

Thanks a lot.

**Comment by kittiu** [comment]
@damendieta OK, I will do it today. Meanwhile, just let you know that, the only PR I am working on is this PR. The budget_management was the old naming, I did change the name to budget_control.

**Comment by kittiu** [comment]
@damendieta let me know if you have problem, I will address one by one.
Please find the readme file.
https://github.com/ecosoft-odoo/account-budgeting/tree/12.0-add-budget_control/budget_control/readme

**Comment by kittiu** [comment]
@damendieta any comment +/- ?

**Comment by kittiu** [comment]
@rvalyi if you have sometime, would you pay a comment to this PR.
If I am not mistaken, I think you did ask something related to mis_builder_budget and budgeting.
You can start from here, https://github.com/OCA/account-budgeting/issues/36
or
https://github.com/ecosoft-odoo/account-budgeting/tree/12.0-add-budget_control/budget_control/readme
I do think in Government sector, this process could be much needed. But it seem it does not caught much attention. I afraid we are reinventing the wheel or going wrong direction.
Thank you!

**Comment by kittiu** [comment]
Closed as moved to experiment in v14

**Pull request closed without merging**
